### ISSUE TITLE
Stable/working release?

### ISSUE THREAD

**Issue by prj** [MEAT-Inc/FulcrumShim#237]
Should the latest release work? Or is it just in development right now, so it is not supposed to work yet?

It started exactly once, pressing on any J2534 DLL it either says "No Devices Found" or the application crashes immediately.
`Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at SharpWrapper.J2534Api.J2534ApiInstance.PassThruGetLastError(System.Text.StringBuilder)
   at SharpWrapper.J2534Api.J2534ApiInstance.InitNexTPassThruDevice()
   at SharpWrapper.J2534Objects.J2534Dll.FindConnectedSDevices()
   at SharpWrapper.J2534Objects.J2534Dll.FindConnectedDeviceNames()
   at FulcrumInjector.FulcrumViewContent.FulcrumViewModels.InjectorCoreViewModels.FulcrumInstalledHardwareViewModel._populateDevicesForDLL(SharpWrapper.J2534Objects.J2534Dll)
   at FulcrumInjector.FulcrumViewContent.FulcrumViewModels.InjectorCoreViewModels.FulcrumInstalledHardwareViewModel.set_SelectedDLL(SharpWrapper.J2534Objects.J2534Dll)`

After that it is not possible to start the app anymore. UAC prompt gets shown, the process just sits in task manager.
The only way to get the app to show up again, is to kill it in the task manager. Uninstall it and then reinstall it.
Then you can again run it exactly once :D

**Comment by ZacharyWalsh57** [comment]
Well that's a new one....  This is still **heavily** under development, but it's being field tested currently and I've never had that come up. So a couple questions.
1. What version of the app are you using? 
2. Are you running from source thru VS or an installed version? 
3. What DLL are you trying to use? 
4. You're sure you've _actually_ got your device hooked up right? 

Can you go navigate to `C:\Program Files (x86)\MEAT-Inc\FulcrumShim\FulcrumInjector\FulcrumLogs` and grab the latest log file(s) for me? If you could also export the registry keys for PassThruSupport (`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\PassThruSupport.04.04` and `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\PassThruSupport.05.00`) that would be awesome.  

It seems like it's crashing on the initialization routine for the JDevice itself inside the API wrapper. Usually that means the device is reporting something back that I don't understand (quite yet), but I'll throw together a fix if you need one.  Going forward, the Injector app _shouldn't_ have that issue opening anymore.  I put together a fix for that about 2 weeks ago that I had confirmed working. But if it does happen, open up an admin command prompt and type `TASKKILL /F /IM Fulcrum*` and that should kill any leftover background tasks/threads. 

Thanks!

**Comment by ZacharyWalsh57** [comment]
Hey it's all good lol. Appreciate the feedback. I've actually got another person with a similar VCI issue going on right now. 

Either way, glad you got something sorted out
